language: c
os: linux
dist: xenial
install: wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-docker.sh
script: bash -ex .travis-docker.sh
services:
  - docker
env:
  global:
    - TESTS=false
    - PINS="solo5-bindings.dev:. solo5-bindings-hvt.dev:. solo5-bindings-spt.dev:. solo5-bindings-virtio.dev:. solo5-bindings-muen.dev:. solo5-bindings-xen.dev:."
    - POST_INSTALL_HOOK="./.travis-test-mirage.sh"
    - DISTRO=alpine
jobs:
  include:
    - name: OCaml 4.10, Solo5/hvt (amd64)
      arch: amd64
      env: OCAML_VERSION=4.10.0 PACKAGE="solo5-bindings-hvt"
    - name: OCaml 4.09, Solo5/hvt (amd64)
      arch: amd64
      env: OCAML_VERSION=4.09 PACKAGE="solo5-bindings-hvt" EXTRA_ENV="MIRAGE_TEST_MODE=hvt"
    - name: OCaml 4.09, Solo5/hvt, system switch (amd64)
      arch: amd64
      env: OCAML_VERSION=4.09 INSTALL_LOCAL=1 PACKAGE="solo5-bindings-hvt" EXTRA_ENV="MIRAGE_TEST_MODE=hvt"
    - name: OCaml 4.09, Solo5/spt (amd64)
      arch: amd64
      env: OCAML_VERSION=4.09 PACKAGE="solo5-bindings-spt" EXTRA_ENV="MIRAGE_TEST_MODE=spt"
    - name: OCaml 4.09, Solo5/virtio (amd64)
      arch: amd64
      env: OCAML_VERSION=4.09 PACKAGE="solo5-bindings-virtio" EXTRA_ENV="MIRAGE_TEST_MODE=virtio"
    - name: OCaml 4.09, Solo5/muen (amd64)
      arch: amd64
      env: OCAML_VERSION=4.09 PACKAGE="solo5-bindings-muen" EXTRA_ENV="MIRAGE_TEST_MODE=muen"
    - name: OCaml 4.09, Solo5/hvt (arm64)
      arch: arm64
      env: OCAML_VERSION=4.09 PACKAGE="solo5-bindings-hvt" EXTRA_ENV="MIRAGE_TEST_MODE=hvt"
    - name: OCaml 4.09, Solo5/spt (arm64)
      arch: arm64
      env: OCAML_VERSION=4.09 PACKAGE="solo5-bindings-spt" EXTRA_ENV="MIRAGE_TEST_MODE=spt"
    - name: OCaml 4.08, Solo5/hvt (amd64)
      arch: amd64
      env: OCAML_VERSION=4.08 PACKAGE="solo5-bindings-hvt" EXTRA_ENV="MIRAGE_TEST_MODE=hvt"
    - name: OCaml 4.08, Solo5/xen (amd64)
      arch: amd64
      env: OCAML_VERSION=4.08 PACKAGE="solo5-bindings-xen" EXTRA_ENV="MIRAGE_TEST_MODE=xen"
